node {
  def app

  stage('Clone repository') {
    checkout scm
  }

  stage('Build image') {
    app = docker.build(''https://github.com/mizuochi-hikaru/devops_sample_nodejs.git)
  }

  stage('Test') {
    app.inside {
      sh 'npm install --only=dev'
      sh 'npm test'
    }
  }

  stage('Push image') {
    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
      app.push("latest")
    }
  }
}
